version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: acs-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
      - "9600:9600/udp"
      - "8081:8081"
    volumes:
      - ./server:/app/server
      - ./backend/logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SERVER_PATH=/app/server
    networks:
      - acs-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: acs-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - acs-network

networks:
  acs-network:
    driver: bridge 